"""create moods tables

Revision ID: 503564087af0
Revises: 215c30135464
Create Date: 2025-08-30 12:30:15.453576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '503564087af0'
down_revision: Union[str, Sequence[str], None] = '215c30135464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moods',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('visual_scale', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('associated_emotions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mood_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('intensity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mood_id'], ['moods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emotional_triggers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mood_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mood_id'], ['moods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emotional_triggers')
    op.drop_table('associated_emotions')
    op.drop_table('moods')
    # ### end Alembic commands ###
