"""create column registry type on moods table

Revision ID: 75e316efe7ad
Revises: 503564087af0
Create Date: 2025-08-30 13:59:32.184268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75e316efe7ad'
down_revision: Union[str, Sequence[str], None] = '503564087af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moods', sa.Column('registry_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moods', 'registry_type')
    # ### end Alembic commands ###
