# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Continuos Integration

on:
  pull_request:
    branches: [ main ]

jobs:
  security-review:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
          python-version: [ '3.13.5' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Run Trivy vulnerability scanner on repository
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'
          exit-code: '1'

  backend-ci:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: [ '3.13.5' ]
    
    defaults:
      run:
        shell: bash
    
    env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        JWT_ALGORITHM: ${{ secrets.JWT_ALGORITHM }}
        JWT_ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.JWT_ACCESS_TOKEN_EXPIRE_MINUTES }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
    
    - name: Install Python dependencies
      run: make install
      working-directory: backend

    - name: Run backend linter
      run: make lint
      working-directory: backend

    - name: Run backend tests
      run: make test
      working-directory: backend
